language: python
os: linux
arch: arm64
dist: bionic
before_install:
  - sudo apt-get -y install snmp snmp-mibs-downloader && sudo sed -i 's/mibs :/# mibs :/g' /etc/snmp/snmp.conf
matrix:
  include:
    - python: '2.7'
      env: TOXENV=py27-functest
    - python: '3.5'
      env: TOXENV=py35-functest
    - python: '3.6'
      env: TOXENV=py36-functest
    - python: '3.7'
      env: TOXENV=py37-functest,docs,build
    - python: '3.8'
      env: TOXENV=py38-functest
# TODO: figure out how to run pypy jobs
#    - python: 'pypy2.7'
#      env: TOXENV=pypy-functest
#    - python: 'pypy3.5'
#      env: TOXENV=pypy3-functest
install:
  - pip install tox
script:
  - tox
